#Tomcat服务器配置
server:
    port: 80
    servlet:
        context-path: /

#数据库配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&useUnicode=true
        password: youpinchailv
        driver-class-name: com.mysql.jdbc.Driver
        username: root
#mybatis映射文件位置
mybatis:
    mapper-locations: classpath:static/mapper/*.xml

# 日志级别
logging:
    level:
        com.example.demo.dao: DEBUG

#关闭swagger
springfox:
    documentation:
        swagger-ui:
            enabled: false
